// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ferreteria_backend.Data;

#nullable disable

namespace ferreteriabackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230112160342_addUsersToDb")]
    partial class addUsersToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ferreteria_backend.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 1, 12, 13, 3, 42, 223, DateTimeKind.Local).AddTicks(4570),
                            Description = "pega fuerte",
                            ImageUrl = "https://easycl.vtexassets.com/arquivos/ids/160093/120144.jpg?v=637527403541830000",
                            Name = "Martillo",
                            Price = 5000,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 1, 12, 13, 3, 42, 223, DateTimeKind.Local).AddTicks(4627),
                            Description = "ta chido",
                            ImageUrl = "https://pimdatacdn.bahco.com/media/sub624/16a0ffdce467453f.png",
                            Name = "Destornillador",
                            Price = 4000,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 1, 12, 13, 3, 42, 223, DateTimeKind.Local).AddTicks(4630),
                            Description = "ta wena",
                            ImageUrl = "https://png.pngtree.com/element_our/20190602/ourlarge/pngtree-construction-tool-ruler-illustration-image_1425976.jpg",
                            Name = "Cinta de medir",
                            Price = 3000,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 1, 12, 13, 3, 42, 223, DateTimeKind.Local).AddTicks(4632),
                            Description = "NUEVO TALADRO PERCUTOR SKILL 6060 13 Mm 700WATTS VEL VARIABLE + ACCESORIOS MALETIN ELECTRICO HORMIGON ACERO SKILL",
                            ImageUrl = "https://pbs.twimg.com/media/EJ-h_niWoAEXN3e?format=jpg&name=medium",
                            Name = "Taladro Percutor Electrico Bauker",
                            Price = 34000,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ferreteria_backend.Models.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
